### ISSUE TITLE
NormRestartInstance cause  ASSERT INVALID_DESCRIPTOR error

### ISSUE THREAD

**Issue by honglei** [USNavalResearchLaboratory/norm#67]
test code:
```cpp
    NormInstanceHandle instance = NormCreateInstance();
    NormRestartInstance(instance);
```

assert error position: protolib\src\common\protoDispatcher.cpp(2192)
```cpp
bool ProtoDispatcher::InstallBreak()
{
    ASSERT(INVALID_DESCRIPTOR == break_event.GetDescriptor());
```

**Comment by bebopagogo** [comment]
I tried to recreate this issue but I am not having a problem with this call sequence.  I looked at the code and the NormRestartInstance() first stops if needed (which removes/invalidates the break_event descriptor) before it then starts the instance again.  What operating system are you testing with?

**Comment by honglei** [comment]
Env: Win10/VC2022 x64/Python3.10 x64

**Comment by bebopagogo** [comment]
That helped.  I found the issue.  The Windows ProtoEvent::Close() code was resetting the "event_handle" to NULL instead of to INVALID_HANDLE value as it should.    I have committed and pushed a fix to Protolib and updated the NORM git repo accordingly.

Thanks for catching this and let me know if this resolves the issue for you and we can close this item.

**Comment by honglei** [comment]
Problem solved！
